document.getElementById("fair-use-disclaimer").innerHTML = ` <h2>Fair Use Act Disclaimer</h2>
<p>This site is for educational purposes only!!</p>
<p>**FAIR USE**</p> <br>
<p>Copyright Disclaimer under section 107 of the Copyright Act 1976, allowance is made for “fair use” for purposes such as criticism, comment, news reporting, teaching, scholarship, education and research.</p>
<p>Fair use is a use permitted by copyright statute that might otherwise be infringing.&nbsp;</p>
<p>Non-profit, educational or personal use tips the balance in favor of fair use.&nbsp;</p>
<p>FAIR USE DEFINITION:</p>
<p>(Source: http://en.wikipedia.org/wiki/Fair_use)</p>
<p>Fair use is a doctrine in the United States copyright law that allows limited use of copyrighted material without requiring permission from the rights holders, such as for commentary, criticism, news reporting, research, teaching or scholarship. &nbsp;It provides for the legal, non-licensed citation or incorporation of copyrighted material in another author’s work under a four-factor balancing test. &nbsp;The term “fair use” originated in the United States. &nbsp;A similar principle, fair dealing, exists in some other common law jurisdictions. &nbsp;Civil law jurisdictions have other limitations and exceptions to copyright.&nbsp;</p>
<p>U.S. COPYRIGHT OFFICE- FAIR USE DEFINITION</p>
<p>(Source: http://www.copyright.gov/fls/fl102.html)</p>
<p>One of the rights accorded to the owner of copyright is the right to reproduce or to authorize others to reproduce the work in copies or phonorecords. &nbsp;This right is subject to certain limitations found in sections 107 through 118 of the copyright law (title 17, U.S. Code). &nbsp;One of the more important limitations is the doctrine of “fair use”. &nbsp;The doctrine of fair use has developed through a substantial number of court decisions over the years and has been codified in section 107 of the copyright law.&nbsp;</p>
<p>Section 107 contains a list of the various purposes for which the reproduction of a particular work may be considered fair, such as criticism, comment, news reporting, teaching, scholarship, and research. &nbsp;Section 107 also sets out in four factors to be considered in determining whether or not a particular use is fair:<span style="line-height: 1.5em;">&nbsp;</span></p><br>
<p>1. The purpose and character of the use, including whether such use is of commercial nature or is for nonprofit educational purposes</p><br>
<p>2. The nature of the copyrighted work</p><br>
<p>3. The amount and substantiality of the portion used in relation to the copyrighted work as a whole</p><br>
<p>4. The effect of the use upon the potential market for, or value of, the copyrighted work</p><br>
<p>The distinction between fair use and infringement may be unclear and not easily defined. There is no specific number of words, lines, or notes that may safely be taken without permission. Acknowledging the source of the copyrighted material does not substitute for obtaining permission.</p><br>
<p>The 1961 Report of the Register of Copyrights on the General Revision of the U.S. Copyright Law cites examples of activities that courts have regarded as fair use: “quotation of excerpts in a review or criticism for purposes of illustration or comment; quotation of short passages in a scholarly or technical work, for illustration or clarification of the author’s observations; use in a parody of some of the content of the work parodied; summary of an address or article, with brief quotations, in a news report; reproduction by a library of a portion of a work to replace part of a damaged copy; reproduction by a teacher or student of a small part of a work to illustrate a lesson; reproduction of a work in legislative or judicial proceedings or reports; incidental and fortuitous reproduction, in a newsreel or broadcast, of a work located in the scene of an event being reported.”</p><br>
<p>Copyright protects the particular way an author has expressed himself. It does not extend to any ideas, systems, or factual information conveyed in the work.</p><br>
<p>The safest course is always to get permission from the copyright owner before using copyrighted material. The Copyright Office cannot give this permission.</p><br>
<p>When it is impracticable to obtain permission, use of copyrighted material should be avoided unless the doctrine of fair use would clearly apply to the situation. The Copyright Office can neither determine if a certain use may be considered fair nor advise on possible copyright violations. If there is any doubt, it is advisable to consult an attorney.</p><br>
<p>FL-102, Revised September 2010</p><br>
<!--GENERAL DISCLAIM ---------------------------------------------------------------------------------------------------------------------------->
<h2>General Disclaimer</h2>
<p>Last updated <span>[Jan 31, 2022]</span></p>
<p><strong>INTRODUCTION</strong></p>
<p>The information provided by <span>[Feenixbloom Gamelounge and its other entities] </span>(“we,” “us” or “our”) on<span> [Feenixbloom]</span> (www.feenixbloom.com) <span>[and our mobile application if any]</span> is for general informational purposes only. All information on the Site <span>[and our mobile application if any]</span> is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability or completeness of any information on the Site <span>[or our mobile application if any]</span>.</p>
<p>Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the site <span>[or our mobile application if any]</span> or reliance on any information provided on the site <span>[and our mobile application if any]</span>. Your use of the site [and our mobile application if any] and your reliance on any information on the site <span>[and our mobile application if any]</span> is solely at your own risk. This disclaimer was created using Termly’s <a href="https://termly.io/products/disclaimer-generator/"><span style="color: #000000;">Disclaimer Generator</span></a>.</p>
<br>
<p><strong>EXTERNAL LINKS DISCLAIMER FOR WEBSITE</strong></p>
<p>The Site <span>[and our mobile application if any]</span> may contain (or you may be sent through the Site<span> [or our mobile application if any]</span> links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising. Such external links are/ may not be investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability or completeness by us.</p>
<p>We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site or any website or feature linked in any banner or other advertising. We will not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services.</p><br>
<!--PRIVACY POLICY ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
<h2>Privacy Policy</h2>
<p>Last updated <span>[MAR 10, 2022]</span></p>
<p><span>[Feenixbloom Gamelounge and its other entities] </span>(“we,” “us” or “our”) on<span> [Feenixbloom]</span> (www.feenixbloom.com) <span>[and our mobile application if any]</span>  informs you of our policies regarding the collection, use and disclosure of Personal Information we may receive from users of the Site. <span>[and our mobile application if any]</span> While using our Site, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to your name ("Personal Information").</p><br>
<p><strong>COMMUNICATION AND SECURITY</strong></p>
<p>We may use your Personal Information to contact you with newsletters, marketing or promotional materials and other information. The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, there is no guarantee of absolute security.</p>
<br>
<p><strong>PRIVACY POLICY UPDATES</strong></p>
<p>We at [Feenixbloom Gamelounge and its other entities]<span> [and our mobile application if any]</span> reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy periodically. By using our Site you agree and acknowledge any modifications and consent to abide and be bound by the modified Privacy Policy.</p>
<p>We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site or any website or feature linked in any banner or other advertising. We will not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services.</p>`